import turtle as t 
t.Screen()
t.setup(600,500,100,200)
t.bgcolor('light blue')
t.title("Python turtle graphics")
t.shape('turtle')
t.pensize(5)
t.right(30)
t.forward(200)
t.left(30)
t.backward(400)
t.left(90)
t.pensize(3)
t.pencolor('red')
t.forward(200)
t.up()
t.pencolor('green')
t.forward(150)
t.down()
t.left(45)
t.backward(200)
t.done()
try:
    t.bye()
except Terminator:
    print('exit turtle')